rubenkaiser/serverless-offline-eventBridge

- README.md
- package.json
- src/index.js
- added check for fn.events due to another plugin that didnt have an events property
-  `subscribedChecks.push(subscriber.event.pattern['detail-type'].includes(entry.DetailType));` was added because I noticed that all consumers were being fired. I'm sure there is a better way to do this to match AWS Eventbridge pattern matching. Open to suggestions
-  added `convertEntryToEvent()` because I noticed the events didn't match what's in CloudWatch which is then passed to a consuming lambda function. Considered adding a way to do a custom map. Also open to suggestions
- All changes should be backwards compatible
> support DetailType match and convert event

- src/index.js
Check the top-level keys of the Detail object and compare against the pattern. Note: This will not do a deep compare, just the top-level keys.
Sometimes event handlers are implemented in the `(event, context, callback)` pattern, whereas the handler only sent in a fake context, without a fake callback. This change adds that callback, it also logs the output if the debug flag is set in the config.
> Enable detail checking and support callback handler shape

- src/index.js
The eventBus param in serverless.yml is optional, when it's not set it uses the default eventBus. If this param isn't set, the offline eventBridge stops with an error because it always expects this param. My first solution was adding the default eventBus name to the subscriber and entry, but now I check if both are present before adding the eventBus check in the verifyIsSubscribed. Let me know what you think about this.
> Added support for the 'default' eventBus

- src/index.js
Works for me, but one odd thing... 
I can use the scheduler with config like this: 
```
events:
-   schedule:
name: kickOffExtracts
description: Kick off extracts from back ends that are due
rate: rate(${env:SDPO_EXTRACT_RATE, 5} minutes)
```
but equivalent config for event bridge doesn't get the variables substituted:
```
events:
-   eventBridge:
name: kickOffExtracts
description: Kick off extracts from back ends that are due
schedule: rate(${env:SDPO_EXTRACT_RATE, 5} minutes)
```
I haven't figured out how the variables get substituted in serverless.yml yet
> add support for rate(...) schedules

- src/index.js
fixed event handler subscribe log message to output function name instead of undefined.
`Serverless: serverless-offline-aws-eventbridge :: undefined is subscribed`
> fix: log function typo

- src/index.js
**Note: I accidentally opened #20 in the wrong branch. This is the exact same but open from my appropriate local branch.**
According to the version 1.4.1. I've tested and found that `flattenObject` always return the empty object `{}`. This is because the condition `if(!obj.hasOwnProperty(i))` is never true for properties `i` in `obj`.
> fix: flattenObject always return empty object

- src/index.js
In some cases, maybe the length doesn't match but it should fall to the pattern.
For example, detail object is `{id: 'aaa', item: 'bbb'}` while pattern is `{item: 'bbb'}`. This should be accepted.
> fix: verifyIsSubscribed should match subset rather than equal

- README.md
- src/index.js
Add the ability to retry lambda functions, default is to retry 10 times waiting 500ms.
This doesn't try to mimic the behavior in AWS, but adds a simply retry with a configurable max.
PS. I didn't use [promise-retry](https://github.com/IndigoUnited/node-promise-retry) because of both out of date dependencies and that we don't need all the extra random ability that it provides.
> feat: retry lambda

- src/index.js
the event detail matching is broken for arrays, the array index was added to the key because of Object.entries.
This pr fixes that.
> fix: key.0, key.1 for event detail array matching

- .gitignore
- README.md
- src/index.js
This PR introduces support for eventBridge content-based filters, as per described in https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns-content-based-filtering.html
Please refer to documentation update for implementation details/examples.
Also my own use case:
```yaml
functions:
changeListener:
name: changeListener
handler: src/sync.handle
events:
- eventBridge:
eventBus: main
pattern:
source:
- dynamodb.stream
detail:
dynamodb:
Keys:
pk:
S: [ { "prefix": "USER#" } ]
```
> Added support for eventBridge content-based filters

- src/index.js
Fix event filters when trying to match with "false" as an expected value
> Fix event filters when trying to match with "false" as an expected value

- src/index.js
Json payloads are limited to the default 100kb limit defined by `bodyParser`. 
There is an argument that both limits should be set to the 256kb limit enforced by aws for event bridge message payloads.
> Match the payload limit for json

- README.md
- package-lock.json
- package.json
- src/index.js
We're using Docker container to run our stacks locally and we have the issue that each container is placed on its own IP address within the Docker network. This means that the default hostname of `127.0.0.1` does not work and the second stack cannot connect to the existing mock EventBridge.
This PR simply adds a `hostname` config option to allow the user to specify the hostname that it should connect to.
I wasn't sure how you deal with versioning as the `package.json` and `package-lock.json` were a little behind. I've updated them both to `1.6.3`. Please let me know if I should change this. Thanks!
> Support custom hostnames

- src/index.js
This PR resolves an issue with processing duplicate events when the publisher and subscriber are in two different serverless projects, and the publisher rebuilds causing the MQTT client to reconnect. 
This PR now checks that the subscription has been granted, which will be empty in the case of a reconnection / resubscription.
> prevents duplicate events when client reconnects

- package.json
- src/index.js
Return added to break the exceptions handling. That prevents serverless-offline to break when some lambda function throws an error and enables back this plugin's retry strategy
> #43 break flow when handling errors in invokeSubscriber as it broke retris strategy

- src/index.js
To output proper error message in log instead of `[Object Object]`
> Fix error message output in invokeSubscriber log

- README.md
- src/index.js
Add the ability to not throw when retries are exhausted.
Currently if the error is thrown the offline process will either crash if in process, or not handle future events if using worker threads.
This `PR` adds the ability to prevent the error being thrown.
This can be helpful when working locally to prevent process failure, and keeping the error handling in the functions the same as in production where DLQs may be deployed.
> fix: add throwRetryExhausted option

- src/index.js
Currently the anything-but array causes the program to crash when sending an event bridge message. This is a problem because this behavior works in AWS, but not serverless-offline. Fix this by checking if the anything-but object is an array and returning whether the field is not in the array
``` shell
Error: The 0 eventBridge filter is not supported in serverless-offline-aws-eventBridge yet. Please consider submitting a PR to support it.
at ServerlessOfflineAwsEventbridgePlugin.verifyIfValueMatchesEventBridgePattern (.../node_modules/serverless-offline-aws-eventbridge/src/index.js:393:11)
at ServerlessOfflineAwsEventbridgePlugin.verifyIfValueMatchesEventBridgePattern (.../node_modules/serverless-offline-aws-eventbridge/src/index.js:373:20)
at …
```
> fix: check for array in anything-but

- src/index.ts
This PR addresses issue https://github.com/rubenkaiser/serverless-offline-eventBridge/issues/83. With this, `equals-ignore-case`, as documented in Amazon's [EventBridge User Guide](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns-content-based-filtering.html), is supported.
> Added support for equals-ignore-case filter

- README.md
- src/index.ts
Adds support for suffix pattern. Fixes the issue #98 
Syntax:
```
occupation: [ { "suffix": "man" } ]
```
> Added support for suffix
